import PanoramaIcon from '@mui/icons-material/Panorama';
import DirectionsBoatIcon from '@mui/icons-material/DirectionsBoat';
import AirportShuttleIcon from '@mui/icons-material/AirportShuttle';
import LandscapeIcon from '@mui/icons-material/Landscape';
import KayakingIcon from '@mui/icons-material/Kayaking';
import HikingIcon from '@mui/icons-material/Hiking';
import AutoGraphIcon from '@mui/icons-material/AutoGraph';
import { Landscape } from '@mui/icons-material';

export const DatosTours = [
    
    {
        id: "kayak",
        imagen: 'kayak',
        icono: <KayakingIcon/>,
        tour: "Darwin Kayak",
        duracion: " 5:30 Horas",
        incluye: "Translado, Guia, Vianda",
        precio: " $80000",
        salidas: " 09hs",
        link: 'https://walink.co/9fa32e',
        descripcion: "La actividad comienza cuando los buscan en vehículo 4x4 por sus hoteles y luego ya se dirigen al Paraje Charles Fuhr ubicado a 40 km de la ciudad.  Les facilitarán todo el equipamiento necesario que está incluido (trajes secos de gore tex, chaleco salvavidas, botas y guantes). Una vez preparados comienza el kayak por el Río Santa Ceuz que durará 80 min recorriendo 15 km hasta llegar a la Estancia El Rincón. Al llegar a la estancia, se les ofrecerá el almuerzo. Entrada, plato principal, bebida y postre.  Estará siempre acompañado por un guía y se reunirá en la estancia con el resto del grupo para almorzar.",
        src1: "kayak1",
        src2: "kayak2",
        src3: "kayak3",
        },
    {
        id: 'punWa',
        imagen: 'punWa',
        icono: <AirportShuttleIcon/>,
        tour: 'Nativo Experience Punta Walichu',
        duracion: ' 3 Horas',
        incluye: 'Translado - Travesia 4x4 - Guia - Entrada - Almuerzo o Cena',
        precio: ' $50000',
        salidas: '  11hs/17hs',
        link: 'https://walink.co/63ad74',
        descripcion: 'Excursión de mediodía en 4x4 por la costa del Lago Argentino. Ideal para el día de llegada o de partida, tiene un enfoque antropológico, haciendo un recorrido en el tiempo sobre el paso del hombre en estas tierras, re-descubriendo historias de las primeras expediciones y osados que se aventuraron a lo desconocido. A orillas del Lago Argentino nuestros guías dictan una charla acerca de la formación del paisaje del lugar, sobre la fauna y la flora autóctona. Realizamos un ascenso para obtener una increíble imagen panorámica de la ciudad y sus alrededores. Desde ahí apreciamos la extensión del Lago Argentino y la Cordillera de Los Andes. Recorremos a pie (500m) el sitio arqueológico mientras interpretamos el significado de las pinturas rupestres que vemos en las rocas y las técnicas utilizadas para realizarlas. Finalizamos el recorrido disfrutando de una deliciosa comida patagónica en una locación inolvidable.',
        src1: "punWa1",
        src2: "punWa2",
        src3: "punWa3",
    },
    {
        id: 'todoGlaciares',
        imagen: 'todoGlaciares',
        icono: <DirectionsBoatIcon/>,
        tour: 'Todo Glaciares',
        duracion: ' 7 Hora',
        precio: ' $107000',
        salidas: ' 08:30hs',
        incluye: 'Navegacion',
        descripcion: 'La aventura da comienzo en el Puerto de Punta Bandera, a 47 km de El Calafate, en donde se inicia la navegación por el Brazo Norte del Lago Argentino. Atravesando  la Boca del Diablo con destino al Canal Upsala y para navegar entre los grandes témpanos que se desprenden del frente del Glaciar Upsala. Luego ingresan al Canal Spegazzini y momentos después tendrán la primera vista del Glaciar Seco. Continúan  navegando hasta el frente del Glaciar Spegazzini donde también contemplaran los glaciares Heim Sur y Peineta. Nos preparamos para desembarcar en La Base Spegazzini y comenzamos la visita al área caminando a través del sendero del bosque hasta el Refugio Spegazzini. Este sendero de 300 metros cuenta con vistas inigualables de La Bahía de Los Glaciares, en su recorrido podremos disfrutar de estaciones temáticas y miradores.',
        src1: "todoGlaciares1",
        src2: "todoGlaciares2",
        src3: "todoGlaciares3",
    },
    {
        id: 'cerroFrias',
        imagen: 'cerroFrias',
        icono: <LandscapeIcon/>,
        tour: 'Cerro Frias 4x4/Cabalgata',
        duracion: ' 4 Horas',
        precio: ' $ 44000 a $52000',
        salidas: ' 8:30/14/18:30 hs',
        incluye: 'Translado - Actividad a eleccion- Almuerzo/Merienda/Cena (Depende el horario)',
        descripcion: 'Cerro Frías 4x4 y Cabalgata. A 25km de El Calafate, se puede optar por ascender en 4x4 al Cerro Frías hasta dos puntos panorámicos a 450 y 1.030mts snm incluyendo el balcón del Parque Nacional, o realizar una cabalgata a través de vegas y bosques, subiendo los faldeos del Cerro Frías. En ambas excursiones podremos apreciar vistas del Lago Argentino, Torres del Paine, Boca del Diablo y los picos más altos de la Cordillera de los Andes y Cerro Fitz Roy, encontrando en el camino animales silvestres y autóctonos de la zona. Al regresar descendemos por nuestro bosque nativo de lengas en la ladera SudEste del Cerro Frías. "ALMUERZO- $48000": GUISO PATAGONICO + POSTRE. MENU VEGETARIANO DISPONIBLE(SOLICITAR CON ANTELACION). BEBIDAS NO INCLUIDAS. "MERIENDA- $44000": CAFÉ, TÉ O CHOCOLATADA & TARTAS DULCES. "CENA- $52000": SOPA DE VEGETALES + CAZUELA DE CORDERO + POSTRE',
        src1: "cerroFrias1",
        src2: "cerroFrias2",
        src3: "cerroFrias3",
    },    
    {
        id: 'moreno-spirit',
        imagen: 'morenoSpirit',
        icono: <DirectionsBoatIcon/>,
        tour: 'Moreno Spirit',
        duracion: ' 1 Horas',
        precio: ' $19500',
        salidas: ' 10:30/13/14:30 hs',
        incluye: ' Translado - Guia - Servicio de fotografia',
        descripcion: 'Salimos todos los días desde Puerto Moreno (ubicado al pie de las pasarelas del paseo costero) sobre el Canal de los Témpanos. En segundos nuestra embarcación arriba al frente de la pared norte del glaciar, donde se puede apreciar su altura y su tamaño, desde una perspectiva totalmente diferente a lo que se observa desde las pasarelas. Visitamos la zona donde (cada cierta cantidad de años) se produce la famosa ruptura del glaciar, fenómeno que ha hecho que el glaciar Perito Moreno sea conocido a nivel mundial. Luego realizamos una lenta navegación frente a todo el ancho de la pared norte. Si tenemos suerte, podremos observar algún desprendimiento del glaciar.',
        src1: "morenoSpirit2",
        src2: "morenoSpirit1",
        src3: "morenoSpirit3",
    },
    {
        id: 'pasarelas',
        imagen: 'pasarelas',
        icono: <PanoramaIcon/>,
        tour: 'Pasarelas Glaciar Perito Moreno',
        duracion: ' libre',
        precio: ' $ 25000',
        salidas: ' 8:00hs/ 12:00hs',
        incluye: 'Translado - Guia',
        descripcion: 'Esta excursión es la más importante y concurrida de la zona. El glaciar es un espectáculo indescriptible que colma al visitante de asombro y admiración, incluso ya desde el primer avistamiento a varios kilómetros de distancia en el camino. El recorrido desde El Calafate hasta el glaciar es una sucesión de lagos, arroyos, bosques y montañas nevadas. La contemplación de este fenómeno natural deja sin aliento a miles de turistas que llegan desde diversas partes del mundo.',
        src1: "pasarelas1",
        src2: "pasarelas2",
        src3: "pasarelas3",
    },    
    {
        id: 'cerroHuyliche',
        imagen: 'cerroHuyliche',
        icono: <LandscapeIcon/>,
        tour: 'Cerro Huyliche 4x4 y Zipline',
        duracion: ' 4 horas',
        precio: ' $ 52000',
        salidas: ' am-pm A Confirmar',
        incluye: 'Translado - Guia - Equipamiento - Almuerzo/ Merienda/ Cena (Depende el horario)',
        descripcion: 'Desde El Calafate, en tan solo minutos, comenzaremos el ascenso al cordón Huyliche, el recorrido comienza transitando por las laderas del Cañadon del Arroyo Calafate, desde donde podremos avistar la fauna autóctona. Continuaremos recorriendo el sinuoso camino en ascenso rodeado de bloques erráticos, testigos del poder de la erosión de los glaciares hasta el Primer Balcón, escenario de la Era Cenozoica, datada en 65 millones de años de antigüedad. Luego de descender de los vehículos unos minutos, continuaremos hasta el balcón intermedio donde los guías colocarán los equipos.  Este es el punto de inicio del circuito de tirolesas donde comienza la máxima aventura descendiendo el cerro por las 4 líneas de un total de 2920 metros. Continuando el descenso arribaremos a la Estancia Huyliche donde serviremos el almuerzo, merienda o cena según el horario reservado. ** La excursión Cerro Huyliche 4x4 tiene 3 opciones para realizar la bajada: 4x4, Tirolesa o Trekking. Si viaja en familia o con amigos y eligen opciones distintas compartirán el ascenso al cerro en 4x4 y el tiempo en el casco de la Estancia Huyliche. **',
        src1: "cerroHuyliche1",
        src2: "cerroHuyliche2",
        src3: "cerroHuyliche3",
    },    
    {
        id: 'balcones',
        imagen: 'balcones',
        icono: <PanoramaIcon/>,
        tour: 'Balcones del Calafate',
        duracion: ' 3:30 horas',
        precio: ' $ 45000',
        salidas: ' 10:00 hs/ 14:30hs',
        incluye: 'Translado - Guia - Almuerzo/ Merienda (Depende el horario)',
        descripcion: 'La aventura comienza cuando te pasamos a buscar por tu hotel desde allí salimos en viaje a una nueva aventura !!! Emprendemos ruta hacia la estancia Huyliche donde después de atravesar la huella durante 2 hs alcanzaremos una altura de 950 msnm llegando a Balcones. Desde este punto panorámico privilegiado podrán apreciar la belleza del paisaje, la inmensidad del Lago Argentino, vista de la Ciudad de El Calafate, naciente del Glaciar Perito Moreno y los cerros Fitz Roy y Torre (insignias de El Chalten). También se podrán observar hermosos paisajes, podrán fotografiar cóndores, águilas y zorros entre otros animales autóctonos. Luego haremos una caminata de 20m entre formaciones rocosas únicas, bosques erráticos y la predominante estepa Patagonia. Mas tarde llegaremos al refugio donde disfrutaran de una cálida bienvenida y podran degustar del almuerzo con bebidas incluidas, o una merienda patagónica. ALMUERZO: BIFE A LA CRIOLLA (CEBOLLA Y MORRÓN) EN SANDWICH O AL PLATO. MERINEDA PATAGONICA: TE, CAFÉ O CHOCOLATADA CON BIZCOCHOS DULCES Y SALADOS.',
        src1: "balcones1",
        src2: "balcones2",
        src3: "balcones3",
    },    
    {
        id: 'chalten',
        imagen: 'chalten',
        icono: <HikingIcon/>,
        tour: 'Chalten Full Day',
        duracion: ' 10 horas',
        precio: ' $ 40000',
        salidas: ' 08hs',
        incluye: 'Translado - Guia - Almuerzo',
        descripcion: 'Sabias que el Chalten es La Capital Nacional de El Trekking? Pasamos a buscarte por el alojamiento a las 8 de la mañana y emprendemos el viaje hacia el chalten. El viaje dura 4 horas y paramos en los miradores para apreciar los maravillosos paisajes. Llegados al chalten Realizaremos el sendero "Mirador de los condores", Luego regresamos al pueblo para disfrutar de un almuerzo en restaurante (no incluye bebidas). Luego de almorzar realizaremos el sendero "Chorrillo del Salto". 16hs emprendemos el regreso a la ciudad del Calafate llegando aproximadamente a las 18hs',
        src1: "chalten1",
        src2: "chalten2",
        src3: "chalten3",
    },    
    {
        id: 'mayoSpirit',
        imagen: 'mayoSpirit',
        icono: <DirectionsBoatIcon/>,
        tour: 'Mayo Spirit Trek',
        duracion: ' 8 horas',
        precio: ' $ 70000',
        salidas: ' 08hs',
        incluye: 'Translado - Guia - servicio de fotografia',
        descripcion: 'Salimos desde el puerto Punta Bandera. Comenzamos a navegar por el Canal de los Témpanos y luego ingresamos al Seno Mayo del Lago Argentino. Desembarcamos en Bahía Toro acompañados por nuestro guía, donde realizamos una caminata interpretativa para observar el bosque andino patagónico. Regresamos a la embarcación y desembarcamos en Cerro Negro. Iniciamos una caminata de unos 1.000 mts, internándonos en el bosque andino patagónico, siguiendo la traza de un arroyo que nos lleva hasta la base del Cerro Negro, desde donde podemos contemplar el maravilloso Glaciar Negro. Luego nos trasladamos hasta el glaciar más famoso de la Patagonia, el Perito Moreno. Único por su belleza e imponencia, ésta enorme masa de hielo nace en el Campo de Hielo Patagónico Sur y recorre 30km de largo hasta llegar y finalizar frente a la Península de Magallanes, sobre el Lago Argentino, donde sus paredes sobrepasan los 60 mts de altura. Realizamos una navegación imperdible que recorre su frente norte y área de la ruptura. Por último, desembarcamos en el Puerto Moreno y recorremos las pasarelas. Regresamos al barco y emprendemos la vuelta al puerto de Punta Bandera.',
        src1: "mayoSpirit1",
        src2: "mayoSpirit2",
        src3: "mayoSpirit3",
    },    
    {
        id: 'calafateNight',
        imagen: 'calafateNight',
        icono: <AutoGraphIcon fontSize='large'/>,
        tour: 'Calafate Night',
        duracion: ' 5 horas',
        precio: ' $ 78000',
        salidas: ' 19hs',
        incluye: 'Translado - Guia - Binoculares - Telescopio - Poncho(Abrigo) - Cena',
        descripcion: 'Redescubrí el cielo como nunca antes!! Una experiencia para las mentes curiosas. Acompañado de telescopios y un astrónomo experto con mas de 10 años de experiencia, aprenderás todo sobre la astronomía, podras observar miles de estrellas, la vía láctea, satélites, mitología y mucho más. ITINERARIO = 19.00hs Búsqueda en los hoteles. 20.00hs Arribo a Estancia Tierras donde podrás visitar los alrededores de la estancia y conocerás la historia del lugar, sus costumbres y mucho más. 20.30hs Cena con vista panorámica de los cerros que rodean la estancia.    Cena con modalidad "Buffet Libre de Pastas" Incluye pastas largas, lasagna a la bolognesa, sorrentinos o ravioles, ñoquis. (Opcion vegetariana/vegana)     Acompañado de las mejores salsas como 4 quesos, salsa blanca, bolognesa, fileto. Tambien incluye postre, una bebida de vino cada 2 personas o una bebida gaseosa o agua mineral por persona. 22.00hs Observación del cielo y estrellas. Cerca de las 22 hs habrá una proyección fílmica de 15 minutos para introducir a las personas a la astronomía. Luego se verá el cielo, y el astrónomo les guiará como mirar el cielo, utilizar el telescopio, aprender sobre la vía láctea, nebulosas, estrellas, constelaciones, mitología, y más. También se hará fotografía nocturna y Light Painting.       00.00hs Regreso a hoteles',
        src1: "calafateNight1",
        src2: "calafateNight2",
        src3: "calafateNight3",
    },    
    {
        id: 'kayakGlaciar',
        imagen: 'kayakGlaciar',
        icono: <KayakingIcon/>,
        tour: 'Kayak Glaciar Perito Moreno',
        duracion: ' 9 horas',
        precio: ' Consultar ',
        salidas: ' 10:30hs',
        incluye: 'Translado - Guia - Snacks - Equipamiento',
        descripcion: 'Actividad única en el mundo donde se realiza Kayaking entre Icebergs dentro del Parque Nacional Los Glaciares.La experiencia de realizar kayak frente al Glaciar Perito Moreno es única, permitiendo navegar entre témpanos y visitar la pared norte de este glaciar como nunca antes se hizo. Esta excursión de día  Completo comienza a las 10:30 am con la recogida en los hoteles, llegaremos al Parque Nacional Los Glaciares, aproximadamente a las 12.00.hs. Para comenzar la travesía los guías le proporcionarán el equipo necesario: un traje seco Gore-Tex, traje térmico, botas, guantes y chaleco salvavidas...  te encontrarás navegando con tu kayak frente al Glaciar Perito Moreno, una experiencia que nunca olvidarás.',
        src1: "kayakGlaciar1",
        src2: "kayakGlaciar2",
        src3: "kayakGlaciar3",
    },    
    {
        id: 'cityWalichu',
        imagen: 'cityWalichu',
        icono: <Landscape/>,
        tour: 'City Tour & Punta Walichu',
        duracion: ' 3 horas',
        precio: ' $18000 ',
        salidas: ' 09:00hs/15:00hs',
        incluye: 'Translado - Guia',
        descripcion: 'Comenzamos con la visita a Punta Walichu, sitio arqueológico ubicado a 8 Km. de la localidad, que te mostrará las huellas de los primeros hombres que caminaron estas tierras. Una caminata a lo largo de los aleros y las cuevas te permitirá observar pinturas rupestres (originales y reproducciones) así como una excepcional vista del Lago Argentino y la Cordillera de los Andes. El circuito transita también las principales calles del casco antiguo del pueblo, mostrándote las típicas primeras construcciones de los pioneros así como los edificios del centro cívico actuales. El guía será el responsable de transportarte en el tiempo hacia la historia de los primeros pobladores, te mostrara la flora, la fauna y otros interesantes detalles que atesora esta pequeña Villa Turística. Realizarás una visita por el Paseo Costero y la Bahía Redonda, a metros de la costa del Lago Argentino, en donde podrás observar la abundante avifauna local. Como última escala, en el Centro de Interpretación Histórica observarás a través de una visita auto-guiada, los hechos de mayor relevancia histórica desde las glaciaciones al presente.',
        src1: "cityWalichu1",
        src2: "cityWalichu2",
        src3: "cityWalichu3",
    },    

]

export function getTour(id) {
    return DatosTours.find((DatosTour) => DatosTour.id === id)
}